### ISSUE TITLE
Using on non-blog, non-Wordpress site

### ISSUE THREAD

**Issue by Jakobud** [achingbrain/php5-akismet#4]
I'm attempting to use your lib on a non-blog, non-Wordpress site.  I'm developing a affiliate network coupon and money savings website with various offers for coupons and products.  Each offer allows comments to be left.  This is what I'm testing.

The user only inputs a message.  No email or website or anything else.  I run my comments through the Akismet class and don't get a lot of stuff flagged that I would expect.  For example, if I type a comment as:

"visit my site for free prescription medication! www.myspamsite.com"

`$akismet->isCommentSpam()` returns false.  I would highly expect it to pick something like this as spam.  Is this just a problem with Akismet?

I verified that the library is working by leaving a random comment like "adskafjsldfjalsjd" and it does return true, showing that this is spam.

Any clues on this?

**Comment by achingbrain** [comment]
For whatever reason the Akismet service doesn't consider that to be spam, in which case you should use the <code>$akismet->submitSpam()</code> method to train it.  The PHP class is sadly not privy to the inner workings of the service so can't say why a given piece of text is or isn't spam.

Not much help, sorry.
